### PR TITLE
Support to print view konfig as properties (to easily filter on comma…

### PR DESCRIPTION
**Pull request by ronnierap**
One can now use:

`kreate v flat for properties/flat view`
or 
`kreate v y for yaml view` (`kreate v` will still use yaml as default view

flat/properties view will look like:
```
val.HttpProbes.readiness_failureThreshold=1
val.HttpProbes.readiness_path=bc/actuator/info
val.HttpProbes.readiness_periodSeconds=2
val.HttpProbes.readiness_port=8080
val.HttpProbes.readiness_scheme=HTTP
```
which you can also easily 'grep' and you can still easily see in which section certein values were present

### CODE REVIEW

**Comment by MarkHooijkaas** [comment]
I really like this functionality. I see many uses.

I do have a few small suggestions.
1. the name "property" for me is a bit generic (I think it is named after java properties that often have this format, but is not universal). I thought the p was for path. aliases could still be p/path/prop/properties (but might be confusing overkill). This is mostly personal taste
2. A nice extra would be `view prop [<pattern>]` to search for certain pattern (or patterns?). This avoids the pipe to grep which you might want to do often
3. I saw the new package (flatdict) in requirements. In general I like to minimize dependencies, and was wondering if we can not implement this in a few lines (including the grep), reducing one dependency (not sure if it is a "big" dependency)

**Comment by ronnierap** [comment]
Thanks for the feedback:

1. What would you perhaps suggest? maybe f for flat would be the alternative?
2. Like the idea, this way you do it in a more generic way.
3. We can definitely do without, I guess. Lets try it.

So what do you think about flat instead of prop?

**Comment by ronnierap** [comment]
Fixed remark 3. now using a local method for flattening; remove the flatDict dependency.

**Comment by ronnierap** [comment]
Also renamed prop to flat for a flat view ;-)

And added support for patterns in path filters.
For example you can search on `kreate v flat val.HttpProbes=8080`

This will return in the example given only:
```
val.HttpProbes.readiness_port=8080
```

And as it's an regex you should be able to do:
`kreate v flat val.HttpProbes="8[0-9]80"`

**Pull request merged**
